-- ==========================================
-- MASTER DATA SEED SCRIPT
-- Database: placement_management_db
-- Schema: Database Design v1.0 (frozen)
--
-- Reference-only validation datasets:
--   skill_categories.csv / sheet -> skills.category
--   company_industries.csv / sheet -> companies.industry
--
-- Actual seeded PostgreSQL tables:
--   roles, branches, job_roles, skills, companies, interview_stages
--
-- UUID primary keys are omitted so PostgreSQL generates them via
-- gen_random_uuid() as defined by the frozen schema.
-- ==========================================

BEGIN;

-- ==========================================
-- 1. Roles (4 records)
-- ==========================================
INSERT INTO roles (role_name, description)
VALUES
    ('Student', 'User who manages a profile, explores opportunities, applies to placements, and uses career readiness features.'),
    ('Recruiter', 'Company representative who manages recruitment activities, evaluates candidates, and updates hiring outcomes.'),
    ('Placement Officer', 'Placement team member who manages placement drives, coordinates stakeholders, and monitors placement activities.'),
    ('System Administrator', 'Authorized system user who manages platform configuration, users, access, and system-level operations.')
ON CONFLICT (role_name) DO NOTHING;

-- ==========================================
-- 2. Branches (20 records)
-- ==========================================
INSERT INTO branches (branch_name, branch_code, department)
VALUES
    ('Artificial Intelligence and Data Science', 'AIDS', 'Engineering'),
    ('Artificial Intelligence and Machine Learning', 'AIML', 'Engineering'),
    ('Computer Science and Engineering', 'CSE', 'Engineering'),
    ('Computer Science and Information Technology', 'CSIT', 'Engineering'),
    ('Information Technology', 'IT', 'Engineering'),
    ('Computer Engineering', 'CE', 'Engineering'),
    ('Electronics and Telecommunication Engineering', 'ENTC', 'Engineering'),
    ('Electronics and Communication Engineering', 'ECE', 'Engineering'),
    ('Electrical Engineering', 'EE', 'Engineering'),
    ('Electrical and Electronics Engineering', 'EEE', 'Engineering'),
    ('Mechanical Engineering', 'ME', 'Engineering'),
    ('Civil Engineering', 'CIVIL', 'Engineering'),
    ('Chemical Engineering', 'CHE', 'Engineering'),
    ('Biomedical Engineering', 'BME', 'Engineering'),
    ('Instrumentation Engineering', 'IE', 'Engineering'),
    ('Production Engineering', 'PE', 'Engineering'),
    ('Industrial Engineering', 'IEG', 'Engineering'),
    ('Aerospace Engineering', 'AE', 'Engineering'),
    ('Automobile Engineering', 'AUTO', 'Engineering'),
    ('Mechatronics Engineering', 'MEC', 'Engineering')
ON CONFLICT (branch_code) DO NOTHING;

-- ==========================================
-- 3. Job Roles (75 records)
-- ==========================================
-- The frozen schema has no UNIQUE constraint on role_title.
-- NOT EXISTS prevents duplicate role_title rows on repeated seed runs.
INSERT INTO job_roles (role_title, category, description)
SELECT v.role_title, v.category, v.description
FROM (VALUES
    ('Software Engineer', 'Software Development', 'Develops, tests, and maintains software applications and services.'),
    ('Software Developer', 'Software Development', 'Builds and maintains software solutions based on technical requirements.'),
    ('Associate Software Engineer', 'Software Development', 'Supports software development, testing, debugging, and maintenance.'),
    ('Graduate Engineer Trainee (GET)', 'Software Development', 'Works under structured training while developing engineering and software skills.'),
    ('Trainee Software Engineer', 'Software Development', 'Receives practical training while contributing to software development tasks.'),
    ('System Engineer', 'Software Development', 'Designs, implements, and maintains computing systems and technical solutions.'),
    ('Programmer Analyst', 'Software Development', 'Develops software solutions while analyzing business and technical requirements.'),
    ('Backend Developer', 'Software Development', 'Builds server-side applications, APIs, services, and data-access components.'),
    ('Frontend Developer', 'Software Development', 'Develops responsive and interactive user interfaces for web applications.'),
    ('Full Stack Developer', 'Software Development', 'Develops both client-side and server-side components of web applications.'),
    ('Python Developer', 'Software Development', 'Builds applications and services using Python.'),
    ('Java Developer', 'Software Development', 'Develops enterprise and backend applications using Java.'),
    ('Web Developer', 'Software Development', 'Creates and maintains websites and web applications.'),
    ('Mobile Application Developer', 'Software Development', 'Develops applications for mobile platforms and devices.'),
    ('Application Developer', 'Software Development', 'Designs and develops application software for business or user requirements.'),
    ('Software Architect', 'Software Architecture', 'Defines software architecture, technical structure, and design standards.'),
    ('Solutions Architect', 'Software Architecture', 'Designs technology solutions that satisfy business and technical requirements.'),
    ('Technical Consultant', 'Consulting', 'Provides technical guidance and recommends technology solutions.'),
    ('AI Engineer', 'Artificial Intelligence', 'Designs and implements AI-powered applications and intelligent systems.'),
    ('AI Research Engineer', 'Artificial Intelligence', 'Develops and evaluates AI methods and prototypes through research-oriented engineering.'),
    ('Machine Learning Engineer', 'Machine Learning', 'Builds, deploys, and maintains machine learning models and pipelines.'),
    ('Deep Learning Engineer', 'Machine Learning', 'Develops deep learning models for complex prediction and pattern recognition.'),
    ('NLP Engineer', 'Artificial Intelligence', 'Develops systems that process and understand human language.'),
    ('Computer Vision Engineer', 'Artificial Intelligence', 'Develops systems for image and video understanding.'),
    ('Generative AI Engineer', 'Artificial Intelligence', 'Builds applications using generative AI models and related technologies.'),
    ('MLOps Engineer', 'Machine Learning', 'Automates and manages development, deployment, and operation of ML systems.'),
    ('AI Product Engineer', 'Artificial Intelligence', 'Builds production-ready products integrating artificial intelligence.'),
    ('AI Solutions Engineer', 'Artificial Intelligence', 'Implements AI solutions aligned with business and technical requirements.'),
    ('Data Scientist', 'Data Science', 'Uses statistical and machine learning methods to extract insights and build models.'),
    ('Data Analyst', 'Data Science', 'Analyzes data and communicates insights for business decisions.'),
    ('Data Engineer', 'Data Engineering', 'Builds and maintains data pipelines, platforms, and processing systems.'),
    ('Data Quality Analyst', 'Data Science', 'Evaluates data accuracy, completeness, consistency, and quality.'),
    ('Business Intelligence Analyst', 'Business Intelligence', 'Analyzes business data and develops decision-support insights.'),
    ('Business Intelligence Developer', 'Business Intelligence', 'Develops data models, dashboards, and reporting solutions.'),
    ('Data Visualization Specialist', 'Data Science', 'Creates visual representations of data to communicate insights.'),
    ('Database Developer', 'Database', 'Designs, develops, and optimizes database structures and queries.'),
    ('Database Administrator', 'Database', 'Manages database availability, security, performance, backups, and maintenance.'),
    ('Cloud Engineer', 'Cloud Computing', 'Designs, deploys, and manages cloud infrastructure and applications.'),
    ('Cloud Solutions Engineer', 'Cloud Computing', 'Implements cloud-based solutions based on technical requirements.'),
    ('Cloud Architect', 'Cloud Computing', 'Designs scalable, secure, and reliable cloud architecture.'),
    ('DevOps Engineer', 'DevOps', 'Automates software delivery, infrastructure management, and operations.'),
    ('Site Reliability Engineer', 'DevOps', 'Improves system reliability, availability, scalability, and performance.'),
    ('Platform Engineer', 'DevOps', 'Builds and maintains internal platforms supporting software delivery.'),
    ('DevSecOps Engineer', 'Cyber Security', 'Integrates security practices into development and DevOps processes.'),
    ('QA Engineer', 'Quality Assurance', 'Tests software to identify defects and verify quality requirements.'),
    ('Automation Test Engineer', 'Quality Assurance', 'Develops automated tests to improve testing efficiency and coverage.'),
    ('Software Test Engineer', 'Quality Assurance', 'Plans and executes tests to validate software requirements.'),
    ('Performance Test Engineer', 'Quality Assurance', 'Evaluates software performance, scalability, and stability under load.'),
    ('Cyber Security Analyst', 'Cyber Security', 'Monitors systems and investigates security events and threats.'),
    ('Security Engineer', 'Cyber Security', 'Designs and implements controls protecting systems and applications.'),
    ('Penetration Tester', 'Cyber Security', 'Performs authorized security testing to identify vulnerabilities.'),
    ('Security Operations Center Analyst', 'Cyber Security', 'Monitors security events and supports incident detection and response.'),
    ('Application Security Engineer', 'Cyber Security', 'Identifies and mitigates security risks in software applications.'),
    ('Network Security Engineer', 'Cyber Security', 'Designs and maintains controls protecting organizational networks.'),
    ('UI/UX Designer', 'Design', 'Designs user interfaces and experiences focused on usability.'),
    ('Product Designer', 'Design', 'Designs digital product experiences based on user and business needs.'),
    ('Product Manager', 'Product Management', 'Defines product direction, priorities, and requirements.'),
    ('Associate Product Manager', 'Product Management', 'Supports product planning, research, prioritization, and delivery.'),
    ('Business Analyst', 'Business Analysis', 'Analyzes business requirements and translates them into actionable needs.'),
    ('Technical Business Analyst', 'Business Analysis', 'Bridges business requirements and technical implementation through analysis.'),
    ('Systems Analyst', 'Business Analysis', 'Analyzes business systems and defines technology-based improvements.'),
    ('Project Coordinator', 'Project Management', 'Coordinates project activities, schedules, communication, and documentation.'),
    ('Technical Project Manager', 'Project Management', 'Manages technical projects across scope, schedule, resources, and delivery.'),
    ('IT Support Engineer', 'IT Support', 'Provides technical support and resolves hardware, software, and system issues.'),
    ('Technical Support Engineer', 'IT Support', 'Diagnoses and resolves technical issues for products and services.'),
    ('Network Engineer', 'Infrastructure', 'Designs, configures, and maintains computer networks.'),
    ('System Administrator', 'Infrastructure', 'Maintains operating systems, servers, access, and IT infrastructure.'),
    ('Embedded Software Engineer', 'Embedded Systems', 'Develops software for embedded systems and resource-constrained devices.'),
    ('IoT Engineer', 'Embedded Systems', 'Develops connected device solutions using sensors, networks, and IoT platforms.'),
    ('Robotics Engineer', 'Robotics', 'Develops software and control systems for robotic applications.'),
    ('Research Scientist', 'Research', 'Conducts research and develops technical solutions through experimentation.'),
    ('Technical Writer', 'Technical Communication', 'Creates clear technical documentation for software and technical processes.'),
    ('ERP Consultant', 'Enterprise Applications', 'Implements and supports enterprise resource planning solutions.'),
    ('CRM Developer', 'Enterprise Applications', 'Develops and customizes customer relationship management applications.'),
    ('Blockchain Developer', 'Emerging Technologies', 'Develops decentralized applications using blockchain technologies.')
) AS v(role_title, category, description)
WHERE NOT EXISTS (
    SELECT 1 FROM job_roles jr
    WHERE jr.role_title = v.role_title
);

-- ==========================================
-- 4. Skills (250 records)
-- ==========================================
-- category_name was validated exactly against skill_categories.
INSERT INTO skills (skill_name, category)
VALUES
    ('AI Agents', 'Artificial Intelligence'),
    ('Artificial Intelligence', 'Artificial Intelligence'),
    ('Computer Vision', 'Artificial Intelligence'),
    ('Deep Learning', 'Artificial Intelligence'),
    ('Generative AI', 'Artificial Intelligence'),
    ('Image Classification', 'Artificial Intelligence'),
    ('Knowledge Graphs', 'Artificial Intelligence'),
    ('LLMs', 'Artificial Intelligence'),
    ('LangChain', 'Artificial Intelligence'),
    ('LangGraph', 'Artificial Intelligence'),
    ('Named Entity Recognition', 'Artificial Intelligence'),
    ('Natural Language Processing', 'Artificial Intelligence'),
    ('Object Detection', 'Artificial Intelligence'),
    ('Prompt Engineering', 'Artificial Intelligence'),
    ('RAG', 'Artificial Intelligence'),
    ('Recommendation Systems', 'Artificial Intelligence'),
    ('Retrieval-Augmented Generation', 'Artificial Intelligence'),
    ('Speech Recognition', 'Artificial Intelligence'),
    ('Text Classification', 'Artificial Intelligence'),
    ('Transformers', 'Artificial Intelligence'),
    ('API Gateway', 'Backend Development'),
    ('ASP.NET', 'Backend Development'),
    ('Authentication', 'Backend Development'),
    ('Authorization', 'Backend Development'),
    ('Django', 'Backend Development'),
    ('Event-Driven Architecture', 'Backend Development'),
    ('Express.js', 'Backend Development'),
    ('FastAPI', 'Backend Development'),
    ('Flask', 'Backend Development'),
    ('JWT', 'Backend Development'),
    ('Laravel', 'Backend Development'),
    ('Message Queues', 'Backend Development'),
    ('Microservices', 'Backend Development'),
    ('NestJS', 'Backend Development'),
    ('Node.js', 'Backend Development'),
    ('OAuth', 'Backend Development'),
    ('REST API', 'Backend Development'),
    ('Ruby on Rails', 'Backend Development'),
    ('Spring Boot', 'Backend Development'),
    ('Webhooks', 'Backend Development'),
    ('gRPC', 'Backend Development'),
    ('AWS EC2', 'Cloud Computing'),
    ('AWS Lambda', 'Cloud Computing'),
    ('AWS RDS', 'Cloud Computing'),
    ('AWS S3', 'Cloud Computing'),
    ('Amazon Web Services', 'Cloud Computing'),
    ('Azure Blob Storage', 'Cloud Computing'),
    ('Azure Functions', 'Cloud Computing'),
    ('Azure Virtual Machines', 'Cloud Computing'),
    ('Cloud Networking', 'Cloud Computing'),
    ('Cloud Security', 'Cloud Computing'),
    ('Google Cloud Platform', 'Cloud Computing'),
    ('Google Cloud Storage', 'Cloud Computing'),
    ('Google Compute Engine', 'Cloud Computing'),
    ('Infrastructure as a Service', 'Cloud Computing'),
    ('Microsoft Azure', 'Cloud Computing'),
    ('Platform as a Service', 'Cloud Computing'),
    ('Serverless Computing', 'Cloud Computing'),
    ('Software as a Service', 'Cloud Computing'),
    ('Application Security', 'Cyber Security'),
    ('Cryptography', 'Cyber Security'),
    ('Cybersecurity Fundamentals', 'Cyber Security'),
    ('Digital Forensics', 'Cyber Security'),
    ('Ethical Hacking', 'Cyber Security'),
    ('Identity and Access Management', 'Cyber Security'),
    ('Incident Response', 'Cyber Security'),
    ('Malware Analysis', 'Cyber Security'),
    ('Network Monitoring', 'Cyber Security'),
    ('Network Security', 'Cyber Security'),
    ('OWASP', 'Cyber Security'),
    ('OWASP Top 10', 'Cyber Security'),
    ('Penetration Testing', 'Cyber Security'),
    ('Secure Coding', 'Cyber Security'),
    ('Security Auditing', 'Cyber Security'),
    ('Security Operations', 'Cyber Security'),
    ('Threat Modeling', 'Cyber Security'),
    ('Vulnerability Assessment', 'Cyber Security'),
    ('Web Application Security', 'Cyber Security'),
    ('A/B Testing', 'Data Science'),
    ('Business Intelligence', 'Data Science'),
    ('Data Cleaning', 'Data Science'),
    ('Data Mining', 'Data Science'),
    ('Data Modeling', 'Data Science'),
    ('Data Preprocessing', 'Data Science'),
    ('Data Storytelling', 'Data Science'),
    ('Data Visualization', 'Data Science'),
    ('Data Warehousing', 'Data Science'),
    ('ETL', 'Data Science'),
    ('Exploratory Data Analysis', 'Data Science'),
    ('Hypothesis Testing', 'Data Science'),
    ('Linear Algebra', 'Data Science'),
    ('Matplotlib', 'Data Science'),
    ('Microsoft Excel', 'Data Science'),
    ('NumPy', 'Data Science'),
    ('Pandas', 'Data Science'),
    ('Power BI', 'Data Science'),
    ('Predictive Analytics', 'Data Science'),
    ('Probability', 'Data Science'),
    ('Seaborn', 'Data Science'),
    ('Statistical Analysis', 'Data Science'),
    ('Statistics', 'Data Science'),
    ('Tableau', 'Data Science'),
    ('Time Series Analysis', 'Data Science'),
    ('Cassandra', 'Databases'),
    ('Database Design', 'Databases'),
    ('Database Normalization', 'Databases'),
    ('Database Replication', 'Databases'),
    ('DynamoDB', 'Databases'),
    ('Elasticsearch', 'Databases'),
    ('Indexing', 'Databases'),
    ('MariaDB', 'Databases'),
    ('MongoDB', 'Databases'),
    ('MySQL', 'Databases'),
    ('Oracle Database', 'Databases'),
    ('PostgreSQL', 'Databases'),
    ('Redis', 'Databases'),
    ('SQL Query Optimization', 'Databases'),
    ('SQL Server', 'Databases'),
    ('SQLite', 'Databases'),
    ('Stored Procedures', 'Databases'),
    ('Transactions', 'Databases'),
    ('Ansible', 'DevOps'),
    ('Apache HTTP Server', 'DevOps'),
    ('Argo CD', 'DevOps'),
    ('CI/CD', 'DevOps'),
    ('CircleCI', 'DevOps'),
    ('Continuous Integration', 'DevOps'),
    ('Docker', 'DevOps'),
    ('Docker Compose', 'DevOps'),
    ('ELK Stack', 'DevOps'),
    ('GitHub Actions', 'DevOps'),
    ('GitLab CI/CD', 'DevOps'),
    ('Grafana', 'DevOps'),
    ('Helm', 'DevOps'),
    ('Infrastructure as Code', 'DevOps'),
    ('Jenkins', 'DevOps'),
    ('Kubernetes', 'DevOps'),
    ('Linux', 'DevOps'),
    ('Logging', 'DevOps'),
    ('Monitoring', 'DevOps'),
    ('Nginx', 'DevOps'),
    ('Prometheus', 'DevOps'),
    ('Terraform', 'DevOps'),
    ('Angular', 'Frontend Development'),
    ('Ant Design', 'Frontend Development'),
    ('Babel', 'Frontend Development'),
    ('Component-Based Architecture', 'Frontend Development'),
    ('Cypress', 'Frontend Development'),
    ('DOM Manipulation', 'Frontend Development'),
    ('Frontend Testing', 'Frontend Development'),
    ('Jest', 'Frontend Development'),
    ('Material UI', 'Frontend Development'),
    ('Next.js', 'Frontend Development'),
    ('React', 'Frontend Development'),
    ('React Native', 'Frontend Development'),
    ('Redux', 'Frontend Development'),
    ('State Management', 'Frontend Development'),
    ('Svelte', 'Frontend Development'),
    ('Vite', 'Frontend Development'),
    ('Vue.js', 'Frontend Development'),
    ('Webpack', 'Frontend Development'),
    ('Bayesian Inference', 'Machine Learning'),
    ('Classification', 'Machine Learning'),
    ('Clustering', 'Machine Learning'),
    ('Cross-Validation', 'Machine Learning'),
    ('Decision Trees', 'Machine Learning'),
    ('Dimensionality Reduction', 'Machine Learning'),
    ('Ensemble Learning', 'Machine Learning'),
    ('Explainable AI', 'Machine Learning'),
    ('Feature Engineering', 'Machine Learning'),
    ('Feature Selection', 'Machine Learning'),
    ('Hyperparameter Tuning', 'Machine Learning'),
    ('K-Nearest Neighbors', 'Machine Learning'),
    ('Keras', 'Machine Learning'),
    ('LightGBM', 'Machine Learning'),
    ('MLOps', 'Machine Learning'),
    ('Machine Learning', 'Machine Learning'),
    ('Model Deployment', 'Machine Learning'),
    ('Model Evaluation', 'Machine Learning'),
    ('Model Interpretability', 'Machine Learning'),
    ('Naive Bayes', 'Machine Learning'),
    ('OpenCV', 'Machine Learning'),
    ('PyTorch', 'Machine Learning'),
    ('Random Forest', 'Machine Learning'),
    ('Regression', 'Machine Learning'),
    ('Reinforcement Learning', 'Machine Learning'),
    ('Scikit-learn', 'Machine Learning'),
    ('Supervised Learning', 'Machine Learning'),
    ('Support Vector Machines', 'Machine Learning'),
    ('TensorFlow', 'Machine Learning'),
    ('Unsupervised Learning', 'Machine Learning'),
    ('XGBoost', 'Machine Learning'),
    ('Bash', 'Programming Languages'),
    ('C', 'Programming Languages'),
    ('C#', 'Programming Languages'),
    ('C++', 'Programming Languages'),
    ('Dart', 'Programming Languages'),
    ('Go', 'Programming Languages'),
    ('Java', 'Programming Languages'),
    ('JavaScript', 'Programming Languages'),
    ('Kotlin', 'Programming Languages'),
    ('Lua', 'Programming Languages'),
    ('MATLAB', 'Programming Languages'),
    ('Objective-C', 'Programming Languages'),
    ('PHP', 'Programming Languages'),
    ('PowerShell', 'Programming Languages'),
    ('Python', 'Programming Languages'),
    ('R', 'Programming Languages'),
    ('Ruby', 'Programming Languages'),
    ('Rust', 'Programming Languages'),
    ('SQL', 'Programming Languages'),
    ('Scala', 'Programming Languages'),
    ('Swift', 'Programming Languages'),
    ('TypeScript', 'Programming Languages'),
    ('Active Listening', 'Soft Skills'),
    ('Adaptability', 'Soft Skills'),
    ('Analytical Thinking', 'Soft Skills'),
    ('Collaboration', 'Soft Skills'),
    ('Communication', 'Soft Skills'),
    ('Conflict Resolution', 'Soft Skills'),
    ('Creativity', 'Soft Skills'),
    ('Critical Thinking', 'Soft Skills'),
    ('Decision Making', 'Soft Skills'),
    ('Emotional Intelligence', 'Soft Skills'),
    ('Interpersonal Skills', 'Soft Skills'),
    ('Leadership', 'Soft Skills'),
    ('Negotiation', 'Soft Skills'),
    ('Presentation Skills', 'Soft Skills'),
    ('Problem Solving', 'Soft Skills'),
    ('Professional Writing', 'Soft Skills'),
    ('Public Speaking', 'Soft Skills'),
    ('Teamwork', 'Soft Skills'),
    ('Time Management', 'Soft Skills'),
    ('Workplace Ethics', 'Soft Skills'),
    ('Bootstrap', 'Web Development'),
    ('Browser APIs', 'Web Development'),
    ('CSS', 'Web Development'),
    ('GraphQL', 'Web Development'),
    ('HTML', 'Web Development'),
    ('HTTP', 'Web Development'),
    ('HTTPS', 'Web Development'),
    ('OAuth 2.0', 'Web Development'),
    ('OpenAPI', 'Web Development'),
    ('Progressive Web Apps', 'Web Development'),
    ('Responsive Web Design', 'Web Development'),
    ('SEO Fundamentals', 'Web Development'),
    ('Tailwind CSS', 'Web Development'),
    ('Web Accessibility', 'Web Development'),
    ('Web Performance Optimization', 'Web Development'),
    ('WebSockets', 'Web Development')
ON CONFLICT (skill_name) DO NOTHING;

-- ==========================================
-- 5. Companies (50 records)
-- ==========================================
-- industry_name was validated exactly against company_industries.
-- created_at and updated_at are NOT NULL with no defaults in the frozen schema.
-- CURRENT_TIMESTAMP is therefore supplied explicitly.
-- The frozen schema has no UNIQUE constraint on company_name.
-- NOT EXISTS prevents duplicate company_name rows on repeated seed runs.
INSERT INTO companies (company_name, industry, website, headquarters, created_at, updated_at)
SELECT v.company_name, v.industry, v.website, v.headquarters, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM (VALUES
    ('Google', 'Information Technology', 'https://www.google.com', 'Mountain View, California, USA'),
    ('Microsoft', 'Information Technology', 'https://www.microsoft.com', 'Redmond, Washington, USA'),
    ('Amazon', 'E-commerce', 'https://www.amazon.com', 'Seattle, Washington, USA'),
    ('TCS', 'Information Technology', 'https://www.tcs.com', 'Mumbai, Maharashtra, India'),
    ('Infosys', 'Information Technology', 'https://www.infosys.com', 'Bengaluru, Karnataka, India'),
    ('Wipro', 'Information Technology', 'https://www.wipro.com', 'Bengaluru, Karnataka, India'),
    ('Accenture', 'Consulting', 'https://www.accenture.com', 'Dublin, Ireland'),
    ('Capgemini', 'Consulting', 'https://www.capgemini.com', 'Paris, France'),
    ('Cognizant', 'Information Technology', 'https://www.cognizant.com', 'Teaneck, New Jersey, USA'),
    ('IBM', 'Information Technology', 'https://www.ibm.com', 'Armonk, New York, USA'),
    ('Oracle', 'Information Technology', 'https://www.oracle.com', 'Austin, Texas, USA'),
    ('Deloitte', 'Consulting', 'https://www.deloitte.com', 'London, United Kingdom'),
    ('Adobe', 'Information Technology', 'https://www.adobe.com', 'San Jose, California, USA'),
    ('NVIDIA', 'Semiconductor', 'https://www.nvidia.com', 'Santa Clara, California, USA'),
    ('Qualcomm', 'Semiconductor', 'https://www.qualcomm.com', 'San Diego, California, USA'),
    ('Zoho', 'Information Technology', 'https://www.zoho.com', 'Chennai, Tamil Nadu, India'),
    ('HCLTech', 'Information Technology', 'https://www.hcltech.com', 'Noida, Uttar Pradesh, India'),
    ('LTIMindtree', 'Information Technology', 'https://www.ltimindtree.com', 'Mumbai, Maharashtra, India'),
    ('Tech Mahindra', 'Information Technology', 'https://www.techmahindra.com', 'Pune, Maharashtra, India'),
    ('PwC India', 'Consulting', 'https://www.pwc.in', 'Gurugram, Haryana, India'),
    ('EY India', 'Consulting', 'https://www.ey.com/en_in', 'Bengaluru, Karnataka, India'),
    ('KPMG India', 'Consulting', 'https://kpmg.com/in/en/home.html', 'Mumbai, Maharashtra, India'),
    ('SAP', 'Information Technology', 'https://www.sap.com', 'Walldorf, Germany'),
    ('Salesforce', 'Information Technology', 'https://www.salesforce.com', 'San Francisco, California, USA'),
    ('Cisco', 'Information Technology', 'https://www.cisco.com', 'San Jose, California, USA'),
    ('Intel', 'Semiconductor', 'https://www.intel.com', 'Santa Clara, California, USA'),
    ('AMD', 'Semiconductor', 'https://www.amd.com', 'Santa Clara, California, USA'),
    ('Dell Technologies', 'Information Technology', 'https://www.dell.com', 'Round Rock, Texas, USA'),
    ('Hewlett Packard Enterprise', 'Information Technology', 'https://www.hpe.com', 'Spring, Texas, USA'),
    ('ServiceNow', 'Information Technology', 'https://www.servicenow.com', 'Santa Clara, California, USA'),
    ('Atlassian', 'Information Technology', 'https://www.atlassian.com', 'Sydney, Australia'),
    ('VMware', 'Cloud Services', 'https://www.vmware.com', 'Palo Alto, California, USA'),
    ('Uber', 'Information Technology', 'https://www.uber.com', 'San Francisco, California, USA'),
    ('Airbnb', 'E-commerce', 'https://www.airbnb.com', 'San Francisco, California, USA'),
    ('Flipkart', 'E-commerce', 'https://www.flipkart.com', 'Bengaluru, Karnataka, India'),
    ('Razorpay', 'FinTech', 'https://razorpay.com', 'Bengaluru, Karnataka, India'),
    ('Paytm', 'FinTech', 'https://paytm.com', 'Noida, Uttar Pradesh, India'),
    ('PhonePe', 'FinTech', 'https://www.phonepe.com', 'Bengaluru, Karnataka, India'),
    ('JPMorgan Chase', 'Banking', 'https://www.jpmorganchase.com', 'New York, New York, USA'),
    ('Goldman Sachs', 'Banking', 'https://www.goldmansachs.com', 'New York, New York, USA'),
    ('Morgan Stanley', 'Banking', 'https://www.morganstanley.com', 'New York, New York, USA'),
    ('Johnson & Johnson', 'Healthcare', 'https://www.jnj.com', 'New Brunswick, New Jersey, USA'),
    ('Siemens', 'Manufacturing', 'https://www.siemens.com', 'Munich, Germany'),
    ('Bosch', 'Automotive', 'https://www.bosch.com', 'Gerlingen, Germany'),
    ('Tata Motors', 'Automotive', 'https://www.tatamotors.com', 'Mumbai, Maharashtra, India'),
    ('Reliance Industries', 'Manufacturing', 'https://www.ril.com', 'Mumbai, Maharashtra, India'),
    ('Bharti Airtel', 'Telecommunications', 'https://www.airtel.com', 'New Delhi, India'),
    ('Sony', 'Media and Entertainment', 'https://www.sony.com', 'Tokyo, Japan'),
    ('DHL', 'Logistics and Supply Chain', 'https://www.dhl.com', 'Bonn, Germany'),
    ('Pfizer', 'Pharmaceuticals', 'https://www.pfizer.com', 'New York, New York, USA')
) AS v(company_name, industry, website, headquarters)
WHERE NOT EXISTS (
    SELECT 1 FROM companies c
    WHERE c.company_name = v.company_name
);

-- ==========================================
-- 6. Interview Stages (9 records)
-- ==========================================
-- The frozen schema has no UNIQUE constraint on stage_name.
-- NOT EXISTS prevents duplicate stage_name rows on repeated seed runs.
INSERT INTO interview_stages (stage_name, sequence_no)
SELECT v.stage_name, v.sequence_no
FROM (VALUES
    ('Application Screening', 1),
    ('Online Assessment', 2),
    ('Coding Assessment', 3),
    ('Technical Interview', 4),
    ('Managerial Interview', 5),
    ('HR Interview', 6),
    ('Offer Release', 7),
    ('Joining Confirmation', 8),
    ('Quality Checklist', 9)
) AS v(stage_name, sequence_no)
WHERE NOT EXISTS (
    SELECT 1 FROM interview_stages s
    WHERE s.stage_name = v.stage_name
);

COMMIT;

-- ==========================================
-- End of master data seed script
-- ==========================================