import { useState } from 'react';
import { LoadingState, Metric, PageTitle, Ring, SectionHead, Tag } from '../components/ui';
function Recommendation({ number, title, text }) { return <div className="recommend"><span>{number}</span><h4>{title}</h4><p>{text}</p><button className="text-button">See how to improve →</button></div>; }
export default function ResumeAnalyzerPage() {
  const [file, setFile] = useState(null); const [analyzing, setAnalyzing] = useState(false); const [showJD, setShowJD] = useState(false); const [jd, setJd] = useState('');
  const upload = e => setFile(e.target.files?.[0]?.name || 'resume_aryan_sharma.pdf'); const analyze = () => { setAnalyzing(true); setTimeout(() => setAnalyzing(false), 900); };
  return <><PageTitle eyebrow="AI CAREER INTELLIGENCE" title="Resume Analyzer" text="Turn your resume into clear, actionable career insights." /><section className="upload card ai-card"><div className="ai-label">✦ AI RESUME ANALYSIS</div><div className="upload-inner"><div className="upload-icon">↑</div><h3>{file || 'Drop your resume here'}</h3><p>{file ? 'PDF uploaded successfully · Ready for analysis' : 'Drag and drop a PDF, or browse from your device'}</p><div className="upload-actions"><label className="button secondary">Browse PDF<input type="file" accept="application/pdf" onChange={upload} hidden /></label><button className="button" onClick={analyze} disabled={!file || analyzing}>{analyzing ? 'Analyzing your resume…' : '✦ Analyze Resume'}</button></div><small>Supported format: PDF · Maximum file size: 10 MB</small></div></section>
    {analyzing ? <LoadingState text="AI is reviewing your resume…" /> : <><section className="score-summary card"><div><div className="section-kicker">YOUR RESUME SCORE</div><h2>Looking strong, Aryan.</h2><p>Your profile is well structured and ready to stand out with a few targeted improvements.</p><button className="text-button" onClick={() => setShowJD(true)}>Match against a job description →</button></div><Ring value={78} label="ATS Score" sublabel="Good standing" large /></section><section className="metrics-grid"><Metric icon="▣" label="Resume Strength" value="Strong" note="Clear, impact-focused profile" tone="green" /><Metric icon="⌘" label="Keyword Match" value="76%" note="Above average for your field" /><Metric icon="▤" label="Formatting" value="Excellent" note="ATS-friendly structure" tone="purple" /><Metric icon="◈" label="Skills Detected" value="12" note="Across 4 technical areas" tone="amber" /></section><section className="content-grid"><article className="card"><SectionHead title="Skills detected" action="View all" /><div className="tags"><Tag>JavaScript</Tag><Tag>React</Tag><Tag>Python</Tag><Tag>SQL</Tag><Tag>Git</Tag><Tag>REST APIs</Tag><Tag>Figma</Tag><Tag>+5 more</Tag></div></article><article className="card"><SectionHead title="Keywords to add" /><div className="keyword-list"><span><b>Docker</b><small>High demand in target roles</small></span><span><b>CI/CD</b><small>Frequently seen in job descriptions</small></span><span><b>System Design</b><small>Strengthens experienced applications</small></span></div></article></section><section className="recommendations card"><SectionHead title="Personalized AI recommendations" subtitle="Small changes that can make a measurable difference." /><div className="recommend-grid"><Recommendation number="01" title="Add SQL and Power BI" text="Include these skills in your technical skills section for data-oriented roles." /><Recommendation number="02" title="Quantify achievements" text="Add measurable results to your project descriptions wherever possible." /><Recommendation number="03" title="Strengthen impact statements" text="Lead each experience bullet with an action and a clear outcome." /></div></section>{showJD ? <section className="jd card"><SectionHead title="Match to a job description" subtitle="Paste a role description to see exactly where your profile fits." /><textarea value={jd} onChange={e => setJd(e.target.value)} placeholder="Paste the job description here…" /><button className="button" onClick={() => setJd(jd || 'Software engineer job description loaded.')}>Analyze job match</button>{jd ? <div className="jd-results"><Metric icon="◌" label="Skill Match" value="82%" note="9 relevant skills" /><Metric icon="⌘" label="Keyword Match" value="76%" note="Good coverage" /><Metric icon="↗" label="Experience Match" value="90%" note="Strong alignment" /><Metric icon="✦" label="Overall Match" value="81%" note="Promising opportunity" tone="purple" /></div> : null}</section> : null}</>}
  </>;
}
